### ISSUE TITLE
Ip adress illegal

### ISSUE THREAD

**Issue by MercuryMensch** [HvRibbecK/EFT-Loot-Bringer#1]
What i should do?
![image](https://user-images.githubusercontent.com/66737730/84381023-07875880-abf1-11ea-9b85-329d0b5c967f.png)

I don't change code,only build project and copy 2 dll's

**Comment by HvRibbecK** [comment]
Go into 'main.cpp' and check your IPs on line 42 and 43.
You put wrong ones in there.
